1st iteration
Jenkins29/FlightPlannerFinal pull request #2
Opened 2021-09-21 08:47 UTC by Jenkins29

2021-09-22 19:05 UTC, ausmoons requested changes
Testi iziet, bet ir lieki usingi 
![image](https://user-images.githubusercontent.com/53189160/134405953-aa8898e7-14ce-4e51-a04d-d04220adc3bd.png)

2021-09-22 19:05 UTC, ausmoons commented on .vs/VSWorkspaceState.json
> +{
Izņem liekos failus

2021-09-22 19:05 UTC, ausmoons commented on FlightPlannerFinal/Controllers/AdminController.cs
> +            var same = FlightStorage.SameFlightValidation(flight);
same? Ja tas ir bool, tad sākas ar jautājamo vārdu

2021-09-22 19:05 UTC, ausmoons commented on FlightPlannerFinal/Controllers/CustomerController.cs
> +
Lieka tukša rinda

2021-09-22 19:05 UTC, ausmoons commented on FlightPlannerFinal/Controllers/CustomerController.cs
> +            AirportRequest[] arr = new AirportRequest[1];
arr..kas tie pa nosaukumiem.. Nosaukumiem jābūt saprotamiem un ar nozīmi

2021-09-22 19:05 UTC, ausmoons commented on FlightPlannerFinal/Controllers/CustomerController.cs
> +
Tukša lieka rinda. Pārskati visu

2021-09-22 19:05 UTC, ausmoons commented on FlightPlannerFinal/Models/PageResult.cs
> +        public List<Flight> Items { get; set; } = new List<Flight>();
= new List<Flight>(); -- kāpēc ir šis?

2021-09-23 07:04 UTC, Jenkins29 commented
removed unnecessary usings and spaces. Amended variable names to proper conventions. Regarding new List<Flight>() it is there because it was so in the lecture + without it the build fails and the very first test action (clear) does not work. Apologies for the load of extra files, I had to slowly start the next iteration, so in order to push the requested changes I had to delete/change a lot of files around (should've created a new branch, I know).

2021-09-23 12:19 UTC, EdgarsSalmins approved these changes

2021-09-23 12:24 UTC, closed without merging